# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"sedas_client": "1_prep_utils.ipynb",
         "sedas_get_collections": "1_prep_utils.ipynb",
         "sedas_find_datasets": "1_prep_utils.ipynb",
         "sedas_download": "1_prep_utils.ipynb",
         "sedas_extract": "1_prep_utils.ipynb",
         "convert2cog": "1_prep_utils.ipynb",
         "mosaic2cog": "1_prep_utils.ipynb",
         "cogmosaicbands": "1_prep_utils.ipynb",
         "s3_create_client": "1_prep_utils.ipynb",
         "gb": "1_prep_utils.ipynb",
         "s3_single_upload": "1_prep_utils.ipynb",
         "get_rel_dir_s3_paths": "1_prep_utils.ipynb",
         "s3_upload_dir": "1_prep_utils.ipynb",
         "s3_list_objects_paths": "1_prep_utils.ipynb",
         "s3_list_objects": "1_prep_utils.ipynb",
         "clean_up": "1_prep_utils.ipynb",
         "setup_logging": "1_prep_utils.ipynb",
         "run_snap_command": "1_prep_utils.ipynb",
         "prep_novasar": "2_prep_novasar.ipynb"}

modules = ["prep_utils.py",
           "prep_novasar.py"]

doc_url = "https://SatelliteApplicationsCatapult.github.io/ard-workflows/"

git_url = "https://github.com/SatelliteApplicationsCatapult/ard-workflows/tree/master/"

def custom_doc_links(name): return None
